name: Build Godot Project for Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Godot Engine
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
        unzip Godot_v4.3-stable_linux.x86_64.zip
        sudo mv Godot_v4.3-stable_linux.x86_64 /usr/local/bin/godot

    - name: Install Godot Export Templates
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
        mkdir -p ~/.local/share/godot/export_templates/4.3.stable/
        unzip Godot_v4.3-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/4.3.stable/

    - name: Build Godot project (Headless with OpenGL)
      run: |
        godot --headless --rendering-driver opengl3 --export-release "Windows Desktop" build/game.exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/game.exe
