name: Build Godot Project for Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Godot Engine
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.3.0/Godot_v4.3-stable_linux_headless.64.zip
        unzip Godot_v4.3-stable_linux_headless.64.zip
        sudo mv Godot_v4.3-stable_linux_headless.64 /usr/local/bin/godot

    - name: Build Godot project
      run: |
        godot --export "Windows Desktop" build/game.exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/game.exe
