name: Build Godot Project for Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Windows Game
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build Godot Project
      id: build
      uses: manleydev/build-godot-action@v1.4.1
      with:
        name: TDDD23_Game
        preset: "Windows Desktop"
        debugMode: "false"
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: ${{ github.workspace }}/${{ steps.build.outputs.build }}